name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - uses: actions/upload-artifact@v1
      with:
        name: "bibaugust.exe"
        path: "bibaugust.exe"     

      
